server:
  port: 9004

document:
  gramer:
    default:
      prefix: '${'
      suffix: '}'
    prefix: ${GRAMER_PREFIX:${document.gramer.default.prefix}}
    suffix: ${GRAMER_SUFFIX:${document.gramer.default.suffix}}
    customize-list: ${GRAMER_CUSTOMIZE_LIST:%}
    customize-list-string-delimiting: ${GRAMER_CUSTOMIZE_LIST_STRING_DELIMITING:，}

  doc-to-program: C:\\DocumentServer\\docto.exe

  min-inflate-ratio: 0.0